### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kiacolbert** [reactrewind/react-rewind#40]

**Comment by richardbmx** [comment]
@kiacolbert Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by kiacolbert** [comment]
@richardbmx Hi Richard, thanks for reaching out.  We have actually have our logo already, but I would be happy to refer you to some of the other teams from my incubator!
